server:
  servlet:
    context-path: /bnhp-stock-app
  port: 8080

management:
  server:
    port: 9090

spring:
  application:
    name: bnhp-stock-app
  logging:
    level:
      root: INFO
      org.springframework: INFO
      com.example: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true
  version: 1.0.0